# Generated by Django 3.1.1 on 2021-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card',
            field=models.FileField(null=True, upload_to='profile_ids'),
        ),
    ]
